### ISSUE TITLE
录音不到一秒录音文件没有删除

### ISSUE THREAD

**Issue by mafangchao** [gang544043963/LGAudioKit#2]
录音时间过短的时候,文件没有删除,因为你的stopSoundRecord: 这个方法在录音短的时候是这么调用[self performSelector:@selector(stopSoundRecord:) withObject:view afterDelay:1.5f]; 延迟了1.5秒执行,原因应该是让HUD显示1.5秒,这时候再去取录音时间的话,应该是1.5秒之后的时间,你判断删除的逻辑,认为你录音的1.5秒以上 所以不会删除

**Comment by gang544043963** [comment]
已解决，请更新。谢谢你
