### ISSUE TITLE
如何播放在线音频

### ISSUE THREAD

**Issue by jianjianhao** [gang544043963/LGAudioKit#4]

**Comment by gang544043963** [comment]
先下载，再播放

**Comment by yangguanghei** [comment]
下载到的是mp3格式要怎么播放？  需要将mp3转为caf文件吗

**Comment by gang544043963** [comment]
@yangguanghei 可以自己改一下LGAudioPlarer.m文件，就可以支持mp3了

- (NSData *)audioDataFromURLString:(NSString *)URLString atIndex:(NSUInteger)index{
	NSData *audioData;

	if ([URLString hasSuffix:@".caf"] || [URLString hasSuffix:@".wav"]) {//播放本机录制的文件
		audioData = [NSData dataWithContentsOfFile:URLString];
	} else if ([URLString hasSuffix:@".amr"]) {//播放安卓发来的AMR文件
		audioData = DecodeAMRToWAVE([NSData dataWithContentsOfFile:URLString]);
	} else {
		NSLog(@"soundFile not support!");
	}
	
	if (audioData) {
		objc_setAssociatedObject(audioData, &kXMNAudioDataKey, [NSString stringWithFormat:@"%@_%ld",URLString,index], OBJC_ASSOCIATION_COPY);
	}
	
	return audioData;
}

**Comment by gang544043963** [comment]
代码已经更新，支持了.pm3

**Comment by gang544043963** [comment]
感谢@yangguanghei， 已经支持了在线播放功能
